version: '3.8'

volumes:
  pgdata:

services:

  database:
    image: postgres:alpine
    container_name: database
    restart: always
    env_file:
      - .env
    hostname: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/

  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - database
    command: ["python", "main.py"]
    container_name: bot
